#!/usr/bin/env bash
#
# SPDX-License-Identifier: AGPL-3.0

# I don't remember why
# I had this shebang
# so let's have it just in case
# until next test
#!/data/data/com.termux/files/usr/bin/env bash

_bin="$( \
  dirname \
    "$( \
      command \
        -v \
	  "env")")"
_lib="${_bin}/../lib"
_share="${_bin}/../share"
source \
  "${_lib}/libcrash-bash/crash-bash"

_root_requirements() {
  _check_cmd \
    "awk" \
    "gawk"
  _check_cmd \
    "grep"
  _check_cmd \
    "su" || \
  _check_cmd \
    "sudo"
}

# shellcheck disable=SC2034
_global_variables() {
  touch_date=""
  input_command=""
  input_devices=()
  setting_method=""
  device_type=""
  color=""
  quiet=""
}

_root_touch_disable() {
  local \
    _device="${1}" \
    _cmd=()
  _cmd=(
    # "mv"
    "chmod"
      "000"
      "${_device}"
      # "${_device}.disabled"
  )
  su \
    -c \
    "${_cmd[*]}"
}

_root_touch_enable() {
  local \
    _device="${1}" \
    _cmd=()
  _cmd=(
    # "mv"
    "chmod"
      "0660"
      "${_device}"
    # "${_device}.disabled"
    #"${_device}"
  )
  su \
    -c \
    "${_cmd[*]}"
}

_root_touch_status() {
  local \
    _device="${1}" \
    _msg=()
  _msg=(
    "Checking status for ${_device}."
  )
  _msg_info \
    "${_msg[*]}"
  if \
    [ -e "${_device}" ]; then
    echo \
      "enabled"
  elif \
    [ ! -e "${_device}" ] || \
    [ -e "${_device}.disabled" ]; then
    echo \
      "disabled"
  fi
}

_auto_detect_method() {
  local \
    _os \
    _method
  _os="$(
    uname \
      -o)"
  if [[ "${_os}" == "Android" ]]; then
    _method="root"
    if [[ "$(command \
               -v \
               "su")" ]]; then
      _method="root"
    fi
  fi
  echo \
    "${_method}"
}

_touchctl() {
  local \
    _cmd="${1}" \
    _type="${2}" \
    _method="${3}"
    _opts=()
  shift \
    3
  _input_devices=(
    "$@"
  )
  if [[ "${_method}" == "auto" ]]; then 
    _method="$( \
      _auto_detect_method)"
  fi
  for _device in "${_input_devices[@]}"; do
    "_${_method}_touch_${_cmd}" \
      "${_device}" \
      "${_opts[*]}"
  done
}

_input_devices_get() {
  local \
    _cmd=() \
    _out \
    _os \
    _su \
    _msg=() \
    _device=() \
    _index \
    _abs_line \
    _abs_assignment \
    _abs \
    _event \
    _event_line \
    _event_no
  declare \
    -A \
    _devices
  _os="$(
    uname \
      -o)"
  if [[ "${_os}" == "Android" ]]; then
    _msg=(
      "Detected Android OS,"
      "reading input devices requires"
      "root permission."
    )
    _msg_info \
      "${_msg[*]}"
    _cmd=(
      "su"
        "-c"
    )
  fi
  _cmd+=(
    "cat"
      "/proc/bus/input/devices"
  )
  mapfile \
    -d \
    $'\n' \
    _out < \
    <("${_cmd[@]}")
  _index="0"
  for _line in "${_out[@]}"; do
    _text="${_line%$'\n'}"
    if [[ "${_text}" == *": "* ]]; then
      if [[ "${_text}" == "I: "* ]]; then
        _device=(
          "${_text}"
        )
      else
        _device+=(
          "${_text}"
        )
      fi
    else
    # elif [[ "${_text}" == "\n\n" ]]; then
      _devices["${_index}"]="$(
        printf \
          "%s\n" \
          "${_device[@]}")"
      _index="$((
        _index + 1))"
      _msg=(
        "Adding device '${_device}'"
        "to devices list."
      )
    fi
  done
  for _index in "${!_devices[@]}"; do
    _device="${_devices["${_index}"]}"
    _abs_line="$(
      echo \
        "${_device}" |
        grep \
          "^B: ABS=" || \
        true)"
    if [[ "${_abs_line}" != "" ]]; then
      _abs_assignment="$(
        echo \
          "${_abs_line}" |
          awk \
            '{print $2}')"
      _abs="${_abs_assignment#ABS=}"
      if (( 1000 < "${_abs}" )); then
        _event_line="$(
          echo \
            "${_device}" |
            grep \
             "^S: Sysfs")"
        _event="${_event_line##*/}"
        _event_no="${_event##input}"
        _input_devices+=(
          "/dev/input/event${_event_no}"
        )
      fi
    fi
  done
  _msg=(
    "Got devices '${_input_devices[*]}'."
  )
  _msg_info \
    "${_msg[*]}"
}

_input_devices_auto_detect() {
  local \
    _input_devices=() \
    _msg=()
  if [[ "${input_devices[*]}" == "" ]]; then
    _msg=(
      "No input devices in input,"
      "auto-detecting."
    )
    _msg_info \
      "${_msg[*]}"
    _input_devices_get
    input_devices=(
      "${_input_devices[@]}"
    )
  fi
}

_set_overrides() {
  if [[ -v override_color ]]; then
    color="${override_color}"
  elif [[ -z "${color}" ]]; then
    color="n"
  fi
  if [[ -v override_quiet ]]; then
    quiet="${override_quiet}"
  elif [[ -z "${quiet}" ]]; then
    quiet="y"
  fi
  _set_override \
    "device" \
    "type" \
    "touchscreen"
  _input_devices_auto_detect
  _set_override \
    "setting" \
    "method" \
    "root"
}

# Shows configuration options.
_show_config() {
  _msg_info "${app_name} configuration"
  _msg_info "     Touch operation date:   ${touch_date}"
  _msg_info "            Input command:   ${input_command}"
  _msg_info "              Device type:   ${device_type}"
  _msg_info "            Input devices:   ${input_devices[*]}"
  _msg_info "     Touch setting method:   ${setting_method}"
}

# Show help usage, with an exit status.
# $1: exit status number.
_usage() {
  local \
    _usage_text
  IFS='' \
    read \
      -r \
      -d '' \
      _usage_text << \
        ENDUSAGETEXT || true

Touchscreen control

Usage:
  ${app_name}
    [options]
    <command>
  commands:
    enable
    disable
    status
  options:
     -t                   Input device type.
                          It can be 'touchscreen'
                          or 'touchpad'.
                          Default: ${device_type}
     -d                   Input device path.
                          It gets auto-detected when
                          only one touch input device
                          is found.
                          Default: ${input_devices[*]}
     -m                   Setting method (root)
                          Default: ${setting_method}
     -h                   This message.
     -v                   Enable verbose output

ENDUSAGETEXT
  _printf \
    '%s\n' \
    "${_usage_text}"
  exit \
    "${1}"
}

_globals
_global_variables
# shellcheck disable=SC2004
# shellcheck disable=SC2034
while \
  getopts \
    't:d:m:cvh?' \
    arg; do
  case \
    "${arg}" in
    t)
      override_device_type="${OPTARG}" ;;
    d)
      input_devices+=(
        "${OPTARG}"
      ) ;;
    m)
      override_setting_method="${OPTARG}" ;;
    c)
      override_color="y" ;;
    v)
      override_quiet="n" ;;
    h|?)
      _set_overrides
      _usage \
        0 ;;
    *)
      _msg=(
        "Invalid argument '${arg}'."
      )
      _msg_error \
        "${_msg[*]}" \
        0 && \
      _set_overrides
      _usage \
        1
      ;;
  esac
done
shift \
  $((
    OPTIND - 1 \
  ))
if (( $# < 1 )); then
  _set_overrides
  _usage \
    1
fi
input_command="${1}"
_set_overrides
app_opts=(
  "${input_command}"
  "${device_type}"
  "${setting_method}"
  "${input_devices[@]}"
)
_config_user_init \
  "touchctl"
_show_config
_touchctl \
  "${app_opts[@]}"

# vim:set sw=2 sts=-1 et:
